name: Build Typst document
on: [push, workflow_dispatch]

jobs:
  build-thesis-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Japanese fonts (apt)
        run: |
          mkdir ./downloads && cd ./downloads
          sudo apt-get update && sudo apt-get install -y fonts-noto fonts-ipafont unzip wget

      - name: Install Japanese fonts (UDEVGothic)
        run: |
          cd ./downloads
          wget "https://github.com/yuru7/udev-gothic/releases/download/v1.3.1/UDEVGothic_v1.3.1.zip" 
          unzip ./UDEVGothic_v1.3.1.zip
          sudo mkdir -p /usr/share/fonts/truetype/UDEVGothic
          sudo cp UDEVGothic_v1.3.1/*.ttf /usr/share/fonts/truetype/UDEVGothic/
          fc-cache -fvr

      - name: Install Japanese fonts (Source Han Serif JP)
        run: |
          cd ./downloads
          wget "https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/07_SourceHanSerifJ.zip"
          unzip ./07_SourceHanSerifJ.zip
          sudo mkdir -p /usr/share/fonts/opentype/SourceHanSerifJP
          sudo cp OTF/Japanese/*.otf /usr/share/fonts/opentype/SourceHanSerifJP/
          fc-cache -fvr

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            卒論・修論用/main.typ
            リアペ・レポート用/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"

      - name: Date
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date --iso-8601=minutes)" >> $GITHUB_ENV

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto-updated: ${{ env.CURRENT_DATETIME }}"
