name: Build Typst document
on: [push, workflow_dispatch]

jobs:
  build-thesis-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            卒論・修論用/main.typ
            リアペ・レポート用/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"

      - name: Date
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date --iso-8601=minutes)" >> $GITHUB_ENV

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto-updated: ${{ env.CURRENT_DATETIME }}"
